### PR TITLE
Fix #275

### LINKED ISSUE #275: Scorched Sand feature not generate and cannot be placed with command
In version 2.1 Scorched Sand feature does not work. 
Cannot be found in a world with single Desert biome. 
And also cannot be placed with command /place feature wilderwild:scorched_sand... 

image

### PR DESCRIPTION
**Pull request by AViewFromTheTop**

### CODE REVIEW

**Comment by AViewFromTheTop** [comment]
@Treetrain1 @Soro335 fixes #275, just tested.

**Review by Treetrain1 — APPROVED** [review]
LGTM

**Comment by Treetrain1** [comment]
does scorched sand naturally generate? or is it just when lightning strikes?

**Comment by AViewFromTheTop** [comment]
> does scorched sand naturally generate? or is it just when lightning strikes?

both

**Comment by Treetrain1** [comment]
> > does scorched sand naturally generate? or is it just when lightning strikes?
> 
> both

i cant find anything already generated

**Comment by Treetrain1** [comment]
> > > does scorched sand naturally generate? or is it just when lightning strikes?
> > 
> > 
> > both
> 
> i cant find anything already generated

nvm just found one lmao

**Comment by Treetrain1** [comment]
ok this can be merged

then im just gonna release 2.1.1

**Pull request merged**
