### PR TITLE
[1.19.2] Compatibility with MixinExtras 0.3+ / Update for Fabric Loader 0.15

### PR DESCRIPTION
**Pull request by Fourmisain**
We ran into an issue with our 1.19.2 modpack where Wilder Wilds 2.0.6 crashes when used together with other mods using MixinExtras 0.3+ or Fabric Loader 0.15, since it bundles it as well.

This update removes the old shadowed MixinExtras version and instead requires Fabric Loader 0.15.

The build slightly broke because the versions aren't fixed and Loom 1.4 now comes with Vineflower support by default, so I removed the outdated `loom-quiltflower` plugin as well. Also updated the gradle wrapper.

Exact same issue with FrozenLib as well, see https://github.com/FrozenBlock/FrozenLib/pull/37

### CODE REVIEW

**Comment by AViewFromTheTop** [comment]
Once I’m settled in at my next hotel (on vacation currently) I’ll merge and release this. @Treetrain1’s worst nightmare.

**Comment by Treetrain1** [comment]
I’ll look at this tonight

lol we said we wouldn’t update old versions but I guess technically *we* didn’t update it :skull:

**Comment by AViewFromTheEnd** [comment]
> I’ll look at this tonight
> 
> lol we said we wouldn’t update old versions but I guess technically _we_ didn’t update it 💀

POGGGGG

**Comment by AViewFromTheEnd** [comment]
Also dammit I kinda forgot to merge it bruhh
Oh well
Vacation’s been taking all my time tbh

**Comment by Fourmisain** [comment]
Whoo! Already a new release, thanks a lot!
Gonna do a quick test.

...

Ah, sorry to bother but it looks like the new 2.0.7 release still contains the old FrozenLib version, so it doesn't actually work 😢

> Found problematic active MixinExtras instance at net.frozenblock.lib.shadow.com.llamalad7.mixinextras (version 0.2.0-beta.8)

**Comment by AViewFromTheEnd** [comment]
> Whoo! Already a new release, thanks a lot! Gonna do a quick test.
> 
> ...
> 
> Ah, sorry to bother but it looks like the new 2.0.7 release still contains the old FrozenLib version, so it doesn't actually work 😢
> 
> > Found problematic active MixinExtras instance at net.frozenblock.lib.shadow.com.llamalad7.mixinextras (version 0.2.0-beta.8)
> 
> edit: Can be worked around by installing FrozenLib 1.2.7 on top, which is good enough for us! Might still be worth doing another release - think of those poor 3 other people that downloaded the mod too!

Bruhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh
If I wasn’t on vacation I’d be able to fix this so easily I hate thisss

**Pull request merged**
