### PR TITLE
Scorched Sand can be Brushed

### PR DESCRIPTION
**Pull request by AViewFromTheTop**
Please be sure to not remove the stateWithoutDusting from canScorch and canHydrate. There are mixins that use those.

### CODE REVIEW

**Comment by Xfrtrex** [comment]
GUYSSSS MY DAD LITERALLY BAUGHT ME ROOT BEEER!!!!! AAAA

**Comment by Xfrtrex** [comment]
OH OH OH AND It MAKES THIS WEIRD NOISE I LOVE ROOT BEER ICVE NEVER HEARD THIS THIS MUST BE AN EPIC ROOT BEER 

https://user-images.githubusercontent.com/80720298/233238583-0f1df342-2479-4242-b5e0-a92eb3159f44.mp4

**Comment by AViewFromTheTop** [comment]
a

**Review by Treetrain1 — APPROVED** [review]
nice

**Comment by Treetrain1** [comment]
Ima just hope it works and merge it

**Comment by AViewFromTheTop** [comment]
> Ima just hope it works and merge it

Tree why would I add something to WW that doesn’t work
Do you not have faith in me after a year of me working tirelessly on this? As if I haven’t created tons for it?

**Comment by AViewFromTheTop** [comment]
If it didn’t work, and I think it’s been made perfectly clear from my own words and actions, I have *no* problems going in and fixing it if it’s something I’ve already started.

**Pull request merged**
