### PR TITLE
adding a missing null check

### PR DESCRIPTION
**Pull request by noah1510**
This fixes a crash I encountered.
Since the logs indicated a straightforward solution I just fixed it instead of opening an issue.

Here is a crash log if you want to do further investigation on what might have caused this situation in the first place: https://gist.github.com/noah1510/aab95896660d11c1d65ead151f2896dc

### CODE REVIEW

**Comment by AViewFromTheTop** [comment]
i'm honestly curious how that line can even run with the blockstate being null
never happened to me before

**Comment by noah1510** [comment]
I think it was caused by some chunks being broken due to an update in regions unexplored. That being said it somehow happened and this seems to fix it.

**Comment by noah1510** [comment]
I found another null pointer exception this time in a brand new chunk.
The second command fixes that one.

The logs are here: https://gist.github.com/noah1510/64d83a22bb9bd88584958c192f09881e

**Comment by Treetrain1** [comment]
Null pointer exceptions? How dare they exist! This calls for a 100% rewrite in Kotlin with maximum null safety!

**Comment by AViewFromTheTop** [comment]
> Null pointer exceptions? How dare they exist! This calls for a 100% rewrite in Kotlin with maximum null safety!

You are seriously going to drive me absolutely insane please don’t

**Comment by AViewFromTheTop** [comment]
btw is this ready to be merged?

**Pull request merged**
