### PR TITLE
23w16a + Snapped Trees

### PR DESCRIPTION
**Pull request by AViewFromTheTop**

### CODE REVIEW

**Comment by AViewFromTheTop** [comment]
plus the trees lmao

**Comment by AViewFromTheTop** [comment]
@Treetrain1 when i take this out of draft you can copy my changes that fix the 23w16a port

**Comment by AViewFromTheTop** [comment]
> @Treetrain1 when i take this out of draft you can copy my changes that fix the 23w16a port

cause this currently includes dev stuff rn

**Comment by AViewFromTheTop** [comment]
yoooo it works

**Comment by AViewFromTheTop** [comment]
@Soro335 here's a snapped tree

**Comment by AViewFromTheTop** [comment]
another one

**Comment by AViewFromTheTop** [comment]
@Treetrain1 you need to update nbtcrafting

**Comment by AViewFromTheTop** [comment]
IN YOUR FACE TREEEE
I UPDATED LIB, WW, AND NBTCRAFTING TO 23w16A BEFORE YOU EVEN TOUCHED THEM
IN YOUR FAAAAAAAAAAAAACE

**Comment by AViewFromTheTop** [comment]
also how do i upload the jitpack thingy,,

**Comment by AViewFromTheTop** [comment]
oh nvm its automatic nice
well that means this pr can probably be merged lmfao
and uh,,
well
sorry i didnt do a separate update pr without actual content added too

**Comment by Treetrain1** [comment]
> IN YOUR FACE TREEEE I UPDATED LIB, WW, AND NBTCRAFTING TO 23w16A BEFORE YOU EVEN TOUCHED THEM IN YOUR FAAAAAAAAAAAAACE

in your face luna i updated a personal modpack before you even touched it in your face

**Comment by AViewFromTheTop** [comment]
in your face tree the next two months of my life have been ruined over the past three hours yaay

**Comment by Treetrain1** [comment]
https://tenor.com/view/sakuya-izayoi-touhou-timestop-touhou-luna-nights-gif-22177720

**Comment by Treetrain1** [comment]
image

**Comment by AViewFromTheTop** [comment]
am trans
long story for why I’ve come back around that im not sharing but yes I’ve been trans this whole time
just want to get this out of the way
either way why the fuck are hanging tendrils crashing

**Comment by AViewFromTheTop** [comment]
It said something was null with hanging tendrils and idk what

**Comment by AViewFromTheTop** [comment]
@Osmiooo one of Dave Gahan’s daughters is named Stella
search up Stella Rose

**Comment by AViewFromTheTop** [comment]
FYI you should update your git bio

**Comment by Osmiooo** [comment]
> @Osmiooo one of Dave Gahan’s daughters is named Stella search up Stella Rose

whos dave gahan

**Comment by Osmiooo** [comment]
> FYI you should update your git bio

oh shit yeah i didnt realize

**Comment by Osmiooo** [comment]
there we go

**Comment by AViewFromTheTop** [comment]
> whos dave gahan

Giiiiirl come on
Lead singer of Depeche Mode
IMG_0276
I love how he looks from 1993-1997

**Comment by AViewFromTheTop** [comment]
> well i didn't know him

He’s hot

**Comment by AViewFromTheTop** [comment]
Just fixed the remaining crashes I could find

**Comment by AViewFromTheTop** [comment]
loot tables are broken in 1.20+ with no way to fix them

**Comment by AViewFromTheTop** [comment]
> loot tables are broken in 1.20+ with no way to fix them

unless its some ide nonsense

**Comment by AViewFromTheEnd** [comment]
IMG_1125
Alan Wilder in gay clubs alert
(unfortunately he is not gay)

**Comment by AViewFromTheTop** [comment]
and this isnt merged for what reason
its the exact f- same as the others, just ported to the latest snapshot

**Comment by MerpisMe** [comment]
luna calm down, you're doing that thing where you get pissed off at us for no reason

**Comment by AViewFromTheTop** [comment]
the loot table bullshit, i highly doubt is on our side. id appreciate if someone could actually step up and look into it because im apparently no longer fucking obligated to work-
is it fabric? is it mojang? is it actually us? i dont fucking know, but this isnt some fucking problem that will only impact this mod. hell, it could impact everything and that's going to signal a damn downfall of content creation on all six sides.
does *anyone* have evidence on record of this happening to others?
because im isolated from all the talk, i cant find shit's worth of words on the internet, and quite frankly, i really dont care. im just asking.

**Comment by AViewFromTheTop** [comment]
it has nothing to do with being a built in loot table or being registered- that doesn't impact behaviour.
there's nothing else that's changed, but it just refuses to work anyway. im at wit's fucking end with this nonsense and honestly, i should retire and just go back to music at this point.

**Comment by AViewFromTheTop** [comment]
the main thing that's confusing me even more so, our older loot tables work!
what fucking issue just... appears out of nowhere like that? the cabin tables work, but nothing new. yet i've checked, i've done nothing wrong. they're pure vanilla, copied and pasted with minor edits. even when i *do* copy and paste vanilla, fucking hell do i know, this issue happens. either the files are fucked on my side, or some weird bullshit's teasing me.

**Comment by AViewFromTheTop** [comment]
> luna calm down, you're doing that thing where you get pissed off at us for no reason

im not going to calm down im tired of being a fucking angel
im pissed the fuck off at damn near *everyone* and you know what? you all can see it.
im pissed.

**Comment by MerpisMe** [comment]
luna this was part of our agreement
if you can't uphold your end by calming down and quitting this sudden aggression, then i'm not upholding my end by letting you stay here
it doesn't matter if you're pissed off over something else, that does not make it right for you to take it out on us when we haven't even done anything to you

**Comment by MerpisMe** [comment]
Do I make myself clear?

**Comment by AViewFromTheTop** [comment]
yes and i am pissed that i cant find a damn solution to the loot table nonsense

**Comment by AViewFromTheTop** [comment]
i seriously have tried everything and i dont know what the fuck else i can do so id like some help or at least for someone to look into it

**Comment by MerpisMe** [comment]
so that makes it ok to be rude to us? 
i advise you quit this while you're ahead. stop focusing on coding and take a break or something. before things go south.

**Comment by AViewFromTheTop** [comment]
and what separates this pr from the rest its the exact same as the others but on 23w16a
clearly you all arent merging it for some reason and are refusing to tell me why id like to fucking fix whatever issue it is so it can be merged like the rest
that looks like blatant refusal to cooperate or just tossing me aside, considering the other prs were merged just fine
i dont see a single explanation about what i can improve anywhere
and maple i really dont know what else i *have* to do
i can take a break and then ill get depressed so i dont see a point

**Comment by AViewFromTheTop** [comment]
to be entirely clear i am not writing that message with aggression
im just
i dont fucking know ok

**Comment by MerpisMe** [comment]
have you considered that it hasn't been merged because tree forgot about it
or that everyone has been busy

**Comment by MerpisMe** [comment]
like literally why are you doing this again
do NOT assume that things are left untouched because they need improvement. if they need improvement you will be told so.

**Comment by AViewFromTheTop** [comment]
and ive been busy too
i dont show it but i *am,* if i were anyone else you wouldnt see me outside once a week at this point

**Comment by MerpisMe** [comment]
you're missing my point lunaaa
my point is that it's likely been left unchecked because it was either forgotten about or that we've all just been too busy to test it

**Comment by MerpisMe** [comment]
we literally had a whole ass fucking discussion about this and about similar situations 
i really feel like no matter how much i try to tell you these things you just refuse to listen outright
just don't assume stuff like that. calm down. period.

**Comment by AViewFromTheTop** [comment]
a
i replied up there, somewhere
thank you for telling me to calm down
im going to give up on programming for a while because its been doing nothing good for me lately

**Comment by AViewFromTheTop** [comment]
https://www.dropbox.com/s/upx1atmsyrqliww/ROOM_ALAN_VOICE.sf2?dl=0
well here's a little gift
go use this soundfont as you please- just not for commercial work unless you want you ass beaten.

**Comment by AViewFromTheTop** [comment]
maple you never told me we couldn’t have conversations
i literally thanked you for pointing out I needed to calm down and made it clear that I was going to finally force myself to take a break from modding because it’s been driving me batshit insane

**Comment by AViewFromTheTop** [comment]
you literally can’t blame me for trying to have a conversation especially when you never made it clear you didnt want that
im sorry but youre going right back to what you were doing that started getting me all scared again
why are you doing this

**Comment by AViewFromTheTop** [comment]
can you just let us be friends are are you going to continue blaming me for “starting conversations” and calling that manipulation???

**Comment by MerpisMe** [comment]
i did make it clear to you that i didnt want you to try to constantly have conversations with me
ive told you countless times that it made me uncomfortable when you'd do that and you just went right back to it like nothing happened

**Comment by MerpisMe** [comment]
i am NOT calling you starting conversations manipulation, i'm saying that i KNOW how you work and i KNOW that if i try to tell you to stop then you'll just try to manipulate me into forgiving you again like you do EVERY TIME

**Comment by AViewFromTheTop** [comment]
ok so why don’t you *remind* me when i forget about that

**Comment by MerpisMe** [comment]
because i think its a pretty important thing for you to remember on your own
you cant depend on me to do that for you

**Comment by AViewFromTheTop** [comment]
some things are really fucking difficult for me to remember and id told you before this is one of them
you just have to remind me about some things instead of treating me like shit sometimes

**Comment by AViewFromTheTop** [comment]
> because i think its a pretty important thing for you to remember on your own
> you cant depend on me to do that for you

again
i can’t remember absolutely everything
i forget things that *i* say, im not going to be able to remember everything you tell me
ive tried to maintain our boundaries but evidently id only remember those about topics

**Comment by AViewFromTheTop** [comment]
and that’s why i literally set a boundary with myself today, that id stop modding
you flat out told me i was doing that again earlier and my response was id go work on music or something else instead

**Comment by MerpisMe** [comment]
good
then go do that

**Comment by AViewFromTheEnd** [comment]
why are you marking my comments as abuse??
look
i am *done* modding until you want to work on the jellyfish model
youve made it clear that’s going to be a while
i would at least like for us to be able to remain friends
modding is what really gets me fucking stressed and my response to you telling me im starting it again is that im not going to mod
i dont know what other or better response i can give

**Comment by MerpisMe** [comment]
no.
i am not comfortable with remaining friends with you.

**Pull request merged**
