### PR TITLE
Turn Nematocysts into Multiface Clusters

### PR DESCRIPTION
**Pull request by Treetrain1**
makes nematocysts function similar to multiface blocks like sculk veins and glow lichens

right now, the models are a bit broken but im sure that can be fixed pretty easily

### CODE REVIEW

**Comment by MerpisMe** [comment]
> right now, the models are a bit broken but im sure that can be fixed pretty easily

in what ways are the models broken exactly?

**Comment by Treetrain1** [comment]
> > right now, the models are a bit broken but im sure that can be fixed pretty easily
> 
> in what ways are the models broken exactly?

the rotations are 90 degrees offset and the outline is a bit misplaced

**Comment by Treetrain1** [comment]
> > > right now, the models are a bit broken but im sure that can be fixed pretty easily
> > 
> > 
> > in what ways are the models broken exactly?
> 
> the rotations are 90 degrees offset and the outline is a bit misplaced

heres an example
image

**Comment by MerpisMe** [comment]
> > > > right now, the models are a bit broken but im sure that can be fixed pretty easily
> > > 
> > > 
> > > in what ways are the models broken exactly?
> > 
> > 
> > the rotations are 90 degrees offset and the outline is a bit misplaced
> 
> heres an example i have it placed on the two walls image

i guess that's fine then, i can try to fix it
but i feel it might look weird if multiple of them intersect because the model is big enough to do that
i GUESS we could just use a separate model that utilizes the small textures only

**Review by MerpisMe — APPROVED** [review]
sure

**Pull request merged**
