### PR TITLE
Fix #433

### LINKED ISSUE #433: Kicked from server/Packet mismatch
**Description of the Bug Encountered**
Occasionally you will get kicked from a server due to a wilder-wild packet.

**Steps To Reproduce**
NA/inconsistent

**Logs**

[latest.txt](https://github.com/user-attachments/files/17602343/mjka7wz.txt)

**Additional context**
I understand that this is relatively vague, but if the latest log is not enough information, please let me know, and I'll try to provide any information you can ask me for.

### PR DESCRIPTION
**Pull request by Dalethium**
Attempted fix for #433

### CODE REVIEW

**Comment by AViewFromTheTop** [comment]
LMFAOOOO I AM ACTUALLY SO DUMB

**Comment by AViewFromTheTop** [comment]
HOW DID I MISS THAT WHEN I WAS BACKPORTING???

**Comment by Dalethium** [comment]
haha no worries! These things happen

**Comment by AViewFromTheTop** [comment]
In any case, @Dalethium, would you be able to rebase this to merge into the 1.20.4 branch? That’s the last version before the networking changes in vanilla, and of course aren’t affected by this issue.
We always merge from one version downwards, in this case at 1.21.1 down until we reach 1.20.2.

**Comment by Dalethium** [comment]
Sure! One moment

**Comment by Dalethium** [comment]
I'll reopen this with the 1.20.4 branch, I am too lazy to go through the process of rebasing the merge req branch.

**Pull request closed without merging**
