### PR TITLE
Next Update

### LINKED ISSUE #293: Can't place off hand torches while holding axe (versions >= 2.1)
**Description of the Bug Encountered**
Player cannot place torches (on non-log blocks) from off hand while holding an axe in main hand since mod v2.1. Mod version 2.0.6 and lower has expected torch placing behavior.

**Steps To Reproduce**
1. Install WilderWild v2.1 or above.
2. Hold an axe in main hand, hold torch in off hand.
3. Right click on a non-log block to place torch.
4. Axe tries to interact with block instead of placing torch.

**Expected Behavior**
Right clicking on a non-log block places a torch.

**Additional context**
Minecraft v1.20.1
Fabric Loader 0.14.22
fabric-api-0.87.0+1.20.1
WilderWild-2.1-Fabric+1.20.1.jar

### PR DESCRIPTION
**Pull request by AViewFromTheTop**
Closes #293 and #277

### CODE REVIEW

**Comment by AViewFromTheTop** [comment]
guys seriously can we make a pikmin mod
i think it'd be easier to develop it as a branch of ww first and then pull it into another mod once its far enough

**Comment by Treetrain1** [comment]
> guys seriously can we make a pikmin mod i think it'd be easier to develop it as a branch of ww first and then pull it into another mod once its far enough

if we did we would have to be careful about copyright

i feel like entity creation is gonna be pain tho
how do you even make a pikmin mod in a sandbox game

wilder wild

**Comment by AViewFromTheTop** [comment]
Just adding Pikmin themselves and delaying mob deaths until they’re near the player so the Pikmin can bring corpses to you
It’d be more for personal use anyway as opposed to a full release

**Comment by AViewFromTheTop** [comment]
@Treetrain1 let's try to get mesoglea elevators in this, with a config option

**Comment by AViewFromTheTop** [comment]
@Treetrain1 would you be able to fix mesoglea bubble elevators
Basically, the elevators won't continue from mesoglea *into* water, or vice verse (but they do if you're placing the magma/soul sand to make the elevator, they *dont* when the elevator exists and you're placing more water or mesoglea)

**Comment by AViewFromTheTop** [comment]
ive been trying to fix them for a solid hour and cant figure it out

**Comment by AViewFromTheTop** [comment]
what do you all think
mesoglea bubble columns should be finished (unless someone finds bugs)

**Comment by AViewFromTheTop** [comment]
can someone test and bugfix these please

**Comment by AViewFromTheTop** [comment]
trying out ecospherical expansion
honestly i dont feel like it understands what some biomes need to be (savannas especially) but some of it is just PERFECTION
look at this screenshot i wish we did that

**Comment by AViewFromTheTop** [comment]
i dont understand how they got some features to be so location-specific either.
@Treetrain1 @Soro335 any ideas..?

**Comment by AViewFromTheTop** [comment]
also @Soro335 i highly recommend playing with that mod if you want more ideas for tree shapes

**Comment by AViewFromTheTop** [comment]
@Treetrain1 registerInventories has a red outline under new NoInteractionStorage

**Comment by AViewFromTheTop** [comment]
nvm i just didnt merge frozenlib yet

**Comment by AViewFromTheTop** [comment]
[15:14:19] [main/WARN] (FabricLoader/Mixin) Error loading class: net/minecraft/class_5944$1 (java.lang.ClassNotFoundException: net/minecraft/class_5944$1)
[15:14:19] [main/WARN] (FabricLoader/Mixin) @Mixin target net/minecraft/class_5944$1 was not found fabric-rendering-v1.mixins.json:shader.ShaderProgramImportProcessorMixin from mod fabric-rendering-v1
[15:14:19] [main/WARN] (FabricLoader/Mixin) Error loading class: net/minecraft/class_3218$class_5526 (java.lang.ClassNotFoundException: net/minecraft/class_3218$class_5526)
[15:14:19] [main/WARN] (FabricLoader/Mixin) @Mixin target net/minecraft/class_3218$class_5526 was not found fabric-lifecycle-events-v1.mixins.json:ServerWorldServerEntityHandlerMixin from mod fabric-lifecycle-events-v1
[15:14:19] [main/WARN] (FabricLoader/Mixin) Error loading class: net/minecraft/class_638$class_5612 (java.lang.ClassNotFoundException: net/minecraft/class_638$class_5612)
[15:14:19] [main/WARN] (FabricLoader/Mixin) @Mixin target net/minecraft/class_638$class_5612 was not found fabric-lifecycle-events-v1.client.mixins.json:ClientWorldClientEntityHandlerMixin from mod fabric-lifecycle-events-v1
[15:14:19] [main/WARN] (FabricLoader/Mixin) Error loading class: net/minecraft/class_3065$1 (java.lang.ClassNotFoundException: net/minecraft/class_3065$1)
[15:14:19] [main/WARN] (FabricLoader/Mixin) @Mixin target net/minecraft/class_3065$1 was not found fabric-game-rule-api-v1.mixins.json:GameRuleCommandVisitorMixin from mod fabric-game-rule-api-v1
[15:14:19] [main/WARN] (FabricLoader/Mixin) Error loading class: net/minecraft/class_5235$class_5241$1 (java.lang.ClassNotFoundException: net/minecraft/class_5235$class_5241$1)
[15:14:19] [main/WARN] (FabricLoader/Mixin) @Mixin target net/minecraft/class_5235$class_5241$1 was not found fabric-game-rule-api-v1.client.mixins.json:RuleListWidgetVisitorMixin from mod fabric-game-rule-api-v1
[15:14:19] [main/WARN] (FabricLoader/Mixin) Error loading class: net/minecraft/class_8197$class_5305$1 (java.lang.ClassNotFoundException: net/minecraft/class_8197$class_5305$1)
[15:14:19] [main/WARN] (FabricLoader/Mixin) @Mixin target net/minecraft/class_8197$class_5305$1 was not found fabric-biome-api-v1.mixins.json:NetherBiomePresetMixin from mod fabric-biome-api-v1
[15:14:19] [main/WARN] (FabricLoader/Mixin) Error loading class: net/minecraft/class_3244$1 (java.lang.ClassNotFoundException: net/minecraft/class_3244$1)
[15:14:19] [main/WARN] (FabricLoader/Mixin) @Mixin target net/minecraft/class_3244$1 was not found fabric-events-interaction-v0.mixins.json:ServerPlayNetworkHandlerMixin from mod fabric-events-interaction-v0
[15:14:19] [main/WARN] (FabricLoader/Mixin) Error loading class: net/minecraft/class_1088$class_7778 (java.lang.ClassNotFoundException: net/minecraft/class_1088$class_7778)
[15:14:19] [main/WARN] (FabricLoader/Mixin) @Mixin target net/minecraft/class_1088$class_7778 was not found fabric-model-loading-api-v1.mixins.json:ModelLoaderBakerImplMixin from mod fabric-model-loading-api-v1
[15:14:19] [main/WARN] (FabricLoader/Mixin) Error loading class: net/minecraft/class_3898$class_3208 (java.lang.ClassNotFoundException: net/minecraft/class_3898$class_3208)
[15:14:19] [main/WARN] (FabricLoader/Mixin) @Mixin target net/minecraft/class_3898$class_3208 was not found fabric-networking-api-v1.mixins.json:accessor.EntityTrackerAccessor from mod fabric-networking-api-v1
[15:14:20] [main/ERROR] (FabricLoader/Mixin) Mixin apply for mod fabric-crash-report-info-v1 failed fabric-crash-report-info-v1.mixins.json:SystemDetailsMixin from mod fabric-crash-report-info-v1 -> net.minecraft.SystemReport: org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException @Shadow method method_37123 in fabric-crash-report-info-v1.mixins.json:SystemDetailsMixin from mod fabric-crash-report-info-v1 was not located in the target class net.minecraft.SystemReport. Using refmap fabric-crash-report-info-v1-refmap.json
 org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException: @Shadow method method_37123 in fabric-crash-report-info-v1.mixins.json:SystemDetailsMixin from mod fabric-crash-report-info-v1 was not located in the target class net.minecraft.SystemReport. Using refmap fabric-crash-report-info-v1-refmap.json

goddddd i hate when this happens

**Comment by AViewFromTheTop** [comment]
@Treetrain1 how do i fix it i literally cant runclient anymore

**Comment by AViewFromTheTop** [comment]
> [15:14:19] [main/WARN] (FabricLoader/Mixin) Error loading class: net/minecraft/class_5944$1 (java.lang.ClassNotFoundException: net/minecraft/class_5944$1) [15:14:19] [main/WARN] (FabricLoader/Mixin) @mixin target net/minecraft/class_5944$1 was not found fabric-rendering-v1.mixins.json:shader.ShaderProgramImportProcessorMixin from mod fabric-rendering-v1 [15:14:19] [main/WARN] (FabricLoader/Mixin) Error loading class: net/minecraft/class_3218$class_5526 (java.lang.ClassNotFoundException: net/minecraft/class_3218$class_5526) [15:14:19] [main/WARN] (FabricLoader/Mixin) @mixin target net/minecraft/class_3218$class_5526 was not found fabric-lifecycle-events-v1.mixins.json:ServerWorldServerEntityHandlerMixin from mod fabric-lifecycle-events-v1 [15:14:19] [main/WARN] (FabricLoader/Mixin) Error loading class: net/minecraft/class_638$class_5612 (java.lang.ClassNotFoundException: net/minecraft/class_638$class_5612) [15:14:19] [main/WARN] (FabricLoader/Mixin) @mixin target net/minecraft/class_638$class_5612 was not found fabric-lifecycle-events-v1.client.mixins.json:ClientWorldClientEntityHandlerMixin from mod fabric-lifecycle-events-v1 [15:14:19] [main/WARN] (FabricLoader/Mixin) Error loading class: net/minecraft/class_3065$1 (java.lang.ClassNotFoundException: net/minecraft/class_3065$1) [15:14:19] [main/WARN] (FabricLoader/Mixin) @mixin target net/minecraft/class_3065$1 was not found fabric-game-rule-api-v1.mixins.json:GameRuleCommandVisitorMixin from mod fabric-game-rule-api-v1 [15:14:19] [main/WARN] (FabricLoader/Mixin) Error loading class: net/minecraft/class_5235$class_5241$1 (java.lang.ClassNotFoundException: net/minecraft/class_5235$class_5241$1) [15:14:19] [main/WARN] (FabricLoader/Mixin) @mixin target net/minecraft/class_5235$class_5241$1 was not found fabric-game-rule-api-v1.client.mixins.json:RuleListWidgetVisitorMixin from mod fabric-game-rule-api-v1 [15:14:19] [main/WARN] (FabricLoader/Mixin) Error loading class: net/minecraft/class_8197$class_5305$1 (java.lang.ClassNotFoundException: net/minecraft/class_8197$class_5305$1) [15:14:19] [main/WARN] (FabricLoader/Mixin) @mixin target net/minecraft/class_8197$class_5305$1 was not found fabric-biome-api-v1.mixins.json:NetherBiomePresetMixin from mod fabric-biome-api-v1 [15:14:19] [main/WARN] (FabricLoader/Mixin) Error loading class: net/minecraft/class_3244$1 (java.lang.ClassNotFoundException: net/minecraft/class_3244$1) [15:14:19] [main/WARN] (FabricLoader/Mixin) @mixin target net/minecraft/class_3244$1 was not found fabric-events-interaction-v0.mixins.json:ServerPlayNetworkHandlerMixin from mod fabric-events-interaction-v0 [15:14:19] [main/WARN] (FabricLoader/Mixin) Error loading class: net/minecraft/class_1088$class_7778 (java.lang.ClassNotFoundException: net/minecraft/class_1088$class_7778) [15:14:19] [main/WARN] (FabricLoader/Mixin) @mixin target net/minecraft/class_1088$class_7778 was not found fabric-model-loading-api-v1.mixins.json:ModelLoaderBakerImplMixin from mod fabric-model-loading-api-v1 [15:14:19] [main/WARN] (FabricLoader/Mixin) Error loading class: net/minecraft/class_3898$class_3208 (java.lang.ClassNotFoundException: net/minecraft/class_3898$class_3208) [15:14:19] [main/WARN] (FabricLoader/Mixin) @mixin target net/minecraft/class_3898$class_3208 was not found fabric-networking-api-v1.mixins.json:accessor.EntityTrackerAccessor from mod fabric-networking-api-v1 [15:14:20] [main/ERROR] (FabricLoader/Mixin) Mixin apply for mod fabric-crash-report-info-v1 failed fabric-crash-report-info-v1.mixins.json:SystemDetailsMixin from mod fabric-crash-report-info-v1 -> net.minecraft.SystemReport: org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException @shadow method method_37123 in fabric-crash-report-info-v1.mixins.json:SystemDetailsMixin from mod fabric-crash-report-info-v1 was not located in the target class net.minecraft.SystemReport. Using refmap fabric-crash-report-info-v1-refmap.json org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException: @shadow method method_37123 in fabric-crash-report-info-v1.mixins.json:SystemDetailsMixin from mod fabric-crash-report-info-v1 was not located in the target class net.minecraft.SystemReport. Using refmap fabric-crash-report-info-v1-refmap.json
> 
> goddddd i hate when this happens

@Treetrain1 im serious help

**Comment by Treetrain1** [comment]
> > [15:14:19] [main/WARN] (FabricLoader/Mixin) Error loading class: net/minecraft/class_5944$1 (java.lang.ClassNotFoundException: net/minecraft/class_5944$1) [15:14:19] [main/WARN] (FabricLoader/Mixin) @mixin target net/minecraft/class_5944$1 was not found fabric-rendering-v1.mixins.json:shader.ShaderProgramImportProcessorMixin from mod fabric-rendering-v1 [15:14:19] [main/WARN] (FabricLoader/Mixin) Error loading class: net/minecraft/class_3218$class_5526 (java.lang.ClassNotFoundException: net/minecraft/class_3218$class_5526) [15:14:19] [main/WARN] (FabricLoader/Mixin) @mixin target net/minecraft/class_3218$class_5526 was not found fabric-lifecycle-events-v1.mixins.json:ServerWorldServerEntityHandlerMixin from mod fabric-lifecycle-events-v1 [15:14:19] [main/WARN] (FabricLoader/Mixin) Error loading class: net/minecraft/class_638$class_5612 (java.lang.ClassNotFoundException: net/minecraft/class_638$class_5612) [15:14:19] [main/WARN] (FabricLoader/Mixin) @mixin target net/minecraft/class_638$class_5612 was not found fabric-lifecycle-events-v1.client.mixins.json:ClientWorldClientEntityHandlerMixin from mod fabric-lifecycle-events-v1 [15:14:19] [main/WARN] (FabricLoader/Mixin) Error loading class: net/minecraft/class_3065$1 (java.lang.ClassNotFoundException: net/minecraft/class_3065$1) [15:14:19] [main/WARN] (FabricLoader/Mixin) @mixin target net/minecraft/class_3065$1 was not found fabric-game-rule-api-v1.mixins.json:GameRuleCommandVisitorMixin from mod fabric-game-rule-api-v1 [15:14:19] [main/WARN] (FabricLoader/Mixin) Error loading class: net/minecraft/class_5235$class_5241$1 (java.lang.ClassNotFoundException: net/minecraft/class_5235$class_5241$1) [15:14:19] [main/WARN] (FabricLoader/Mixin) @mixin target net/minecraft/class_5235$class_5241$1 was not found fabric-game-rule-api-v1.client.mixins.json:RuleListWidgetVisitorMixin from mod fabric-game-rule-api-v1 [15:14:19] [main/WARN] (FabricLoader/Mixin) Error loading class: net/minecraft/class_8197$class_5305$1 (java.lang.ClassNotFoundException: net/minecraft/class_8197$class_5305$1) [15:14:19] [main/WARN] (FabricLoader/Mixin) @mixin target net/minecraft/class_8197$class_5305$1 was not found fabric-biome-api-v1.mixins.json:NetherBiomePresetMixin from mod fabric-biome-api-v1 [15:14:19] [main/WARN] (FabricLoader/Mixin) Error loading class: net/minecraft/class_3244$1 (java.lang.ClassNotFoundException: net/minecraft/class_3244$1) [15:14:19] [main/WARN] (FabricLoader/Mixin) @mixin target net/minecraft/class_3244$1 was not found fabric-events-interaction-v0.mixins.json:ServerPlayNetworkHandlerMixin from mod fabric-events-interaction-v0 [15:14:19] [main/WARN] (FabricLoader/Mixin) Error loading class: net/minecraft/class_1088$class_7778 (java.lang.ClassNotFoundException: net/minecraft/class_1088$class_7778) [15:14:19] [main/WARN] (FabricLoader/Mixin) @mixin target net/minecraft/class_1088$class_7778 was not found fabric-model-loading-api-v1.mixins.json:ModelLoaderBakerImplMixin from mod fabric-model-loading-api-v1 [15:14:19] [main/WARN] (FabricLoader/Mixin) Error loading class: net/minecraft/class_3898$class_3208 (java.lang.ClassNotFoundException: net/minecraft/class_3898$class_3208) [15:14:19] [main/WARN] (FabricLoader/Mixin) @mixin target net/minecraft/class_3898$class_3208 was not found fabric-networking-api-v1.mixins.json:accessor.EntityTrackerAccessor from mod fabric-networking-api-v1 [15:14:20] [main/ERROR] (FabricLoader/Mixin) Mixin apply for mod fabric-crash-report-info-v1 failed fabric-crash-report-info-v1.mixins.json:SystemDetailsMixin from mod fabric-crash-report-info-v1 -> net.minecraft.SystemReport: org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException @shadow method method_37123 in fabric-crash-report-info-v1.mixins.json:SystemDetailsMixin from mod fabric-crash-report-info-v1 was not located in the target class net.minecraft.SystemReport. Using refmap fabric-crash-report-info-v1-refmap.json org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException: @shadow method method_37123 in fabric-crash-report-info-v1.mixins.json:SystemDetailsMixin from mod fabric-crash-report-info-v1 was not located in the target class net.minecraft.SystemReport. Using refmap fabric-crash-report-info-v1-refmap.json
> > goddddd i hate when this happens
> 
> @Treetrain1 im serious help

close intellij
delete the ".gradle" (not "gradle") folder in the project folder
open intellij
reload gradle

**Comment by AViewFromTheTop** [comment]
IMG_8494
Still pissed about this, and he still has my comment hidden (obviously)

**Comment by Treetrain1** [comment]
just fixed all the baobab nut compatibility issues !!!
image

**Comment by Treetrain1** [comment]
pov kotlin mixin 💀 
image

**Comment by AViewFromTheTop** [comment]
> just fixed all the baobab nut compatibility issues !!!
> image

FOR THE LOVE OF GOD NO

**Comment by AViewFromTheTop** [comment]
DONT MAKE ME GET BACK INTO SUBSTANCE ABUSE TREE

**Comment by AViewFromTheTop** [comment]
IM NOT EVEN JOKING IVE BEEN CLEAN FOR A HANDFUL OF MONTHS DONT MAKE ME GET BACK INTO IT

**Comment by AViewFromTheTop** [comment]
PLEASE NO KOTLIN

**Comment by Treetrain1** [comment]
> DONT MAKE ME GET BACK INTO SUBSTANCE ABUSE TREE

i aint making you do anything 💀

**Comment by AViewFromTheTop** [comment]
another day another gooner sexually harasses me
bruh

**Comment by AViewFromTheTop** [comment]
at some point im just gonna have to stop giving a shit
losers lmao

**Comment by AViewFromTheTop** [comment]
https://github.com/FrozenBlock/WilderWild/assets/87103914/73b9c317-d194-40fd-91b8-3c1e5c38f28d

**Comment by AViewFromTheTop** [comment]
@MerpisMe WHAT DO YOU THINK

**Comment by AViewFromTheTop** [comment]
I didn’t use any synthesizers for this btw (I have one but it never gives me good enough sounds so I don’t use it)

**Comment by AViewFromTheTop** [comment]
The “electronic” beeping is actually feedback of a kick drum sound infinitely looping back into my old amp modeler pedal from the 90s or early 2000s (someone gave it away to me) and I just cleverly added two square tremolos onto it followed by a delay

**Comment by AViewFromTheTop** [comment]
The other sound is that same feedback but for a hihat track, and the chord that plays was an accident when I accidentally un-soloed the hihat track
It actually sounds cool when chopped and edited like that

**Comment by AViewFromTheTop** [comment]
"A third suggestion was that the painting was, in fact, Leonardo’s self-portrait, given the resemblance between the sitter’s and the artist’s facial features. Some scholars suggested that disguising himself as a woman was the artist’s riddle."

Lisa does seem like a pretty good name to use if your deadname's Leonardo lmao
but hasn't it been proven that it's a commission of a cloth merchant's wife

**Comment by Treetrain1** [comment]
> IMG_8722.mov

whats that?

**Comment by Treetrain1** [comment]
im adding a kotlin section to frozenlib

**Comment by AViewFromTheTop** [comment]
> im adding a kotlin section to frozenlib

I’m already suicidal enough today please stop

**Comment by Treetrain1** [comment]
> > im adding a kotlin section to frozenlib
> 
> I’m already suicidal enough today please stop

im adding a section, not replacing stuff with kotlin

so like
a kotlin only section
so that i can move the stuff from configurable everything

image

**Comment by Treetrain1** [comment]
no clue if it will work in prod, ill test that rn

**Comment by Treetrain1** [comment]
image

**Comment by AViewFromTheTop** [comment]
Crisis averted

**Comment by AViewFromTheTop** [comment]
Question
Has anyone found evidence of a Mojang employee playing Wilder Wild

**Comment by Treetrain1** [comment]
> Question Has anyone found evidence of a Mojang employee playing Wilder Wild

i havent

**Comment by Treetrain1** [comment]
im starting to feel its a better idea to not include frozenlib in all fb mods

bc thats a lot of wasted space

**Comment by AViewFromTheTop** [comment]
> im starting to feel its a better idea to not include frozenlib in all fb mods
> 
> bc thats a lot of wasted space

It’s kind of necessary in some cases like WW
My idea is to separate the parts of lib that could be used solely on their own, like the cloth config stuff
it would just be a cloth config extension mod (which gets included in FrozenLib as well)

**Comment by Treetrain1** [comment]
as of 2.1.1 ancient horn cooldowns are broken

the cooldown decreases when i kill a mob lmao

**Comment by AViewFromTheTop** [comment]
> as of 2.1.1 ancient horn cooldowns are broken
> 
> the cooldown decreases when i kill a mob lmao

who changed it

**Comment by AViewFromTheTop** [comment]
I’m genuinely pissed off that I spent all that time trying to get that person to stop arguing over sodium and the moment tree says something so simple they listen
istfg

**Pull request merged**
