### PR TITLE
Snapped Trees

### PR DESCRIPTION
**Pull request by AViewFromTheTop**

### CODE REVIEW

**Comment by Soro335** [comment]
what is snapped trees

**Comment by AViewFromTheTop** [comment]
> what is snapped trees

You'll see
It's like... only the bottom half of a tree

**Comment by AViewFromTheTop** [comment]
holy shit tree's a bottom?>?!?@>>

**Comment by Treetrain1** [comment]
what happened to no more content updates :trollface:

**Comment by AViewFromTheTop** [comment]
> what happened to no more content updates :trollface:

you guys said that
i never did

**Comment by AViewFromTheTop** [comment]
plus, me being separate from main frozenblock means i dont have to work on your newer stuff anyway
im a devoted frozenlib + ww dev

**Review by Treetrain1 — APPROVED** [review]
i totally looked at these in game trust me :trollface:

**Comment by AViewFromTheTop** [comment]
> i totally looked at these in game trust me :trollface:

well i did lmao

**Comment by AViewFromTheTop** [comment]
i whipped these up in like 20 mins and tested once but it works fine
theyre just meant for variation

**Comment by Treetrain1** [comment]
> > i totally looked at these in game trust me :trollface:
> 
> well i did lmao

what it look like

**Comment by AViewFromTheTop** [comment]
> what it look like

dude
snapped trees
thats what they look like
they fucking snapped

**Comment by AViewFromTheTop** [comment]
holy shit they fucking snapped

**Comment by AViewFromTheTop** [comment]
up next: i port frozenlib and ww to 23w16a

**Comment by Treetrain1** [comment]
@AViewFromTheTop 
https://gist.github.com/apple502j/3f46f097b2187bbcca0c6d6ef1ad210a

**Comment by AViewFromTheTop** [comment]
> @AViewFromTheTop https://gist.github.com/apple502j/3f46f097b2187bbcca0c6d6ef1ad210a

I already did it lmao i just used the predictive thing for override and it showed the new method
my pr on frozenlib already has completed 23w16a

**Comment by AViewFromTheTop** [comment]
...unfortunately now i have to do a ton of material and note block nonsense for ww to port to 23w16a properly

**Comment by AViewFromTheTop** [comment]
and yes, i knew about these changes for a while now because i was working on luna 1.20

**Comment by Treetrain1** [comment]
> and yes, i knew about these changes for a while now because i was working on luna 1.20

what is that mod

**Comment by AViewFromTheTop** [comment]
still, ty though cause i dont always update other stuff like that

**Comment by AViewFromTheTop** [comment]
> what is that mod

polishes suspicious blocks, decorated pot texture fix, brush particle polishing, etc

**Comment by AViewFromTheTop** [comment]
whoa what the fuck?!?!?!?!? a mixin inside a mixin
vibration config
how tf did that happen hello!?!!>!>">:

**Comment by AViewFromTheTop** [comment]
judging by the fact it likely works, holy shit
ive never seen that before
though, i cant see myself using it,,

**Comment by AViewFromTheTop** [comment]
aaaaaaaaand lots of vibration changes
fuck

**Pull request merged**
