### PR TITLE
Create ja_jp.json

### PR DESCRIPTION
**Pull request by mayonaka8478**
Translated all except options.

### CODE REVIEW

**Review by Treetrain1 — CHANGES_REQUESTED** [review]
Could you translate the remaining options?

**Comment by AViewFromTheTop** [comment]
This pull request would work much better for the Dev branch, actually.

**Comment by Treetrain1** [comment]
its better than nothing

**Comment by mayonaka8478** [comment]
Sorry for neglecting this for so long.
I will do it when I feel like it.

**Pull request merged**
