### PR TITLE
Add Vietnamese language

### PR DESCRIPTION
**Pull request by godkyo98**

### CODE REVIEW

**Comment by AViewFromTheEnd** [comment]
Hey!
Would you be able to do this for the maple-dev branch instead? en_us.json has new strings needed, and has also been reorganized.

**Comment by godkyo98** [comment]
Yes admin, let me make another branch

**Comment by godkyo98** [comment]
@AViewFromTheEnd is done to new format Bro!

**Comment by AViewFromTheTop** [comment]
> @AViewFromTheEnd is done to new format Bro!

Thank you so much!! I’ll get this merged once I’m home.

**Pull request merged**
