### PR TITLE
TerraBlender Integration

### PR DESCRIPTION
**Pull request by Treetrain1**
This is essentially a rewrite to the TerraBlender branch

This does NOT switch to TerraBlender, however this gives integration for it when the user has TerraBlender installed. If the user does not have TerraBlender, the biomes will be added to generation within the mixin.

Current issues:
Mixed Forests do not generate at the same spots as before. This is due to the forest parameter points being impossible to find.

### CODE REVIEW

**Comment by Treetrain1** [comment]
the biome placement config for swamp and mangrove swamp seem to destroy the placement of cypress wetlands.
im not sure if theres a fix for this issue

**Review by Treetrain1 — COMMENTED** [review]
To change biome parameters with this, the biome parameters must be changed in SharedWorldgen. Both the TerraBlender and Mixin biome generation will change to the parameters set here.

**Comment by MerpisMe** [comment]
so like will this break anything or

**Comment by Treetrain1** [comment]
> so like will this break anything or

no it shouldnt break anything
when the user doesnt have terrablender the biomes will generate with the mixins like how we have it

**Comment by MerpisMe** [comment]
> > so like will this break anything or
> 
> no it shouldnt break anything when the user doesnt have terrablender the biomes will generate with the mixins like how we have it

mk then i think it's fine to merge

**Comment by AViewFromTheTop** [comment]
Works

**Review by AViewFromTheTop — APPROVED** [review]
works

**Comment by AViewFromTheTop** [comment]
whatever apparently nobody wants to touch this repo today so i'm merging and nobody has the right to bitch at me over it

**Comment by Treetrain1** [comment]
> whatever apparently nobody wants to touch this repo today so i'm merging and nobody has the right to bitch at me over it

pog

**Pull request merged**
