### PR TITLE
Next Update

### LINKED ISSUE #286: Coconuts cannot be thrown while looking at a block
**Description of the Bug Encountered**

**Steps To Reproduce**
1. Hold a coconut
2. Look at a block
3. Right-click to throw
4. Nothing happens

**Expected Behavior**

It should be thrown.

**Screenshots**

**Logs**

None needed

**Additional context**

It seems like when you're looking at a block, the coconut's sapling side takes over the projectile side, when the expectation is that if it can't be placed, it should get thrown. It creates an awkward effect where you cannot throw it while looking at a block, which contrasts with vanilla's throwables.
A potential solution is to introduce a separate sapling item crafted with a single coconut, though this likely wouldn't be necessary.

### LINKED ISSUE #289: Mixin config plugin triggers re-entrant game class loads
**Description of the Bug Encountered**

Wilder Wild's Mixin config plugin triggers classloads of other game classes. Because this happens during the prepare phase, it causes classes to be loaded with some transformations not applied.

This was originally discovered through an issue in `better-fabric-console`: https://github.com/jpenilla/better-fabric-console/issues/27#issuecomment-1676430768

**Steps To Reproduce**
1. Install wilder wild
2. Install some other mod with a mixin targeting `n.m.n.c.Component`, such as `adventure-platform-fabric` (here included via `better-fabric-console`
3. launch server
4. perform some method that depends on the transformation to `Component` being properly applied

**Expected Behavior**

Game loads without issues, Mixins to `Component` are applied

**Screenshots**

See upstream issue for history, summary:

debugger outpu

**Logs**

Because of the silent Mixin application failure, you get issues like:
```
[11:17:55 ERROR] [Server thread]: [MinecraftServer] Encountered an unexpected exception
java.lang.NoSuchMethodError: 'net.kyori.adventure.text.Component net.minecraft.class_2561.asComponent()'
        at net.minecraft.server.dedicated.DedicatedServer.sendSystemMessage(DedicatedServer.java:681) ~[?:?]
        at net.minecraft.commands.CommandSourceStack.sendSuccess(CommandSourceStack.java:323) ~[?:?]
        at net.minecraft.server.commands.StopCommand.lambda$register$2(StopCommand.java:16) ~[?:?]
        at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:264) ~[brigadier-1.1.8.jar:?]
        at net.minecraft.commands.Commands.performCommand(Commands.java:287) ~[?:?]
        at net.minecraft.commands.Commands.performPrefixedCommand(Commands.java:280) ~[?:?]
        at net.minecraft.server.dedicated.DedicatedServer.handleConsoleInputs(DedicatedServer.java:299) ~[?:?]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:284) ~[?:?]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:824) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:671) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.lambda$spin$2(MinecraftServer.java:265) ~[server-intermediary.jar:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

**Additional context**

This can probably be pretty easily resolved by splitting the values controlling Mixin application into a separate class with nothing but those fields, and no references to non-loader game classes.

### LINKED ISSUE #294: Add option to prevent rolling tumbleweed to trample crops
Self-explanatory in the title. Even lowering the spawn rates of rolling tumbleweeds (that, btw, have a very wonky physics, but this is subject for a possible another suggestion), they still find a way to end up inside my field (that is surronded by fences, btw), trampling the crops.

A standalone option to make tumbleweeds to not mess with crops is desirable and would prevent me to try to switch `mobGriefing` to `false` and affect lots of other mechanics that i dont like to switch off.

### LINKED ISSUE #295: Add Coconut -> Split coconut recipe for stonecutter
Would be a nice addition, nah?

### PR DESCRIPTION
**Pull request by AViewFromTheTop**
closes #286
closes #289
closes #294
closes #295

### CODE REVIEW

**Comment by Treetrain1** [comment]
no way its the next update

**Comment by Treetrain1** [comment]
i just got an idea for spotting icons

what if we just made them part of a gui and then just render the gui

**Comment by Treetrain1** [comment]
> i just got an idea for spotting icons
> 
> what if we just made them part of a gui and then just render the gui

theoretically that should fix the layering issues

**Comment by AViewFromTheTop** [comment]
> i just got an idea for spotting icons
> 
> what if we just made them part of a gui and then just render the gui

That’s what I wanted to do originally (since PVZGW does it that way) but I have no clue how

**Comment by AViewFromTheTop** [comment]
HOW CAN YOU NOT KNOW THAT ESPECIALLY WHEN YOUVE PLAYED THE MOD

**Comment by Soro335** [comment]
> WHY DOES EVERYONE SAY WILDER WILDS ITS WILDER WILD

I agree, it's very annoying

**Review by Treetrain1 — APPROVED** [review]

**Comment by AViewFromTheTop** [comment]
YEEEEEEEEEES FINALLY FASTANIM IS STARTING TO DECLINE IN POPULARITY AND COPPER PIPES IS TAKING OVER ITS SPOT

**Comment by AViewFromTheTop** [comment]
Do you think itd be funny if FrozenBlock had a mod loader called Fuck My Life

**Pull request merged**
